char *cap_string(char *);
char *create_array(unsigned int size, char c);
char *infinite_add(char *n1, char *n2, char *r, int size_r);
char *_memcpy(char *dest, char *src, unsigned int n);
char *_memset(char *s, char b, unsigned int n);
char *rot13(char *);
char *_strcat(char *dest, char *src);
char *_strchr(char *s, char c);
char *_strcpy(char *dest, char *src);
char *string_toupper(char *);
char *_strncat(char *dest, char *src, int n);
char *_strncpy(char *dest, char *src, int n);
char *_strpbrk(char *s, char *accept);
char *_strstr(char *haystack, char *needle);
int _abs(int n);
int add(int, int);
int _atoi(char *s);
int bigprime(int n);
int coins_denomination(int *deno, int amt, int *coins);
int convert_day(int month, int day);
int factorial(int n);
int _isalpha(int c);
int _isdigit(int c);
int _islower(int c);
int is_palindrome(char *s);
int is_prime_number(int n);
int _isupper(int c);
int largest_number(int a, int b, int c);
int main(int argc, char *argv[]);
int main(void);
int mul(int x, int y);
int _pow_recursion(int x, int y);
int print_last_digit(int);
int print_sign(int n);
int _putchar(char *c);
int _putchar(char c);
int _sqrt_recursion(int n);
int sqrt_root(int root, int number);
int _strcmp(char *s1, char *s2);
int _strlen(char *s);
int _strlen_recursion(char *s);
int wildcmp(char *s1, char *s2);
unsigned int _strspn(char *s, char *accept);
void jack_bauer(void);
void more_numbers(void);
void positive_or_negative(int i);
void print_alphabet(void);
void print_alphabet_x10(void);
void print_array(int *a, int n);
void print_buffer(char *b, int size);
void print_chessboard(char (*a)[8]);
void print_diagonal(int n);
void print_diagsums(int *a, int size);
void print_line(int n);
void print_most_numbers(void);
void print_number(int n);
void print_numbers(void);
void print_remaining_days(int month, int day, int year);
void print_rev(char *s);
void _print_rev_recursion(char *s);
void print_square(int size);
void print_to_98(int n);
void print_triangle(int size);
void puts2(char *str);
void _puts(char *s);
void _puts(char *str);
void puts_half(char *str);
void reset_to_98(int *n);
void reverse_array(int *a, int n);
void rev_string(char *s);
void set_string(char **s, char *to);
void swap_int(int *a,int *b);
void times_table(void);
